"use client";

import type { UseFormRegister, UseFormSetValue, FieldErrors } from "react-hook-form";
import type { OnboardingDraft } from "@/components/features/onboarding/onboarding-wizard";
import { formatMyanmarPhoneInput, normalizeMyanmarPhoneInput } from "@/features/auth/phone-format";
export type ClientDraft = OnboardingDraft;
const industries = ["Tech", "F&B", "Retail", "Fashion", "Media"];

export function ClientOnboardingForm({ register, setValue, errors, industry, phoneValue }: { register: UseFormRegister<ClientDraft>; setValue: UseFormSetValue<ClientDraft>; errors: FieldErrors<ClientDraft>; industry: string; phoneValue: string }) {
  const phoneField = register("phone_number");
  return <div className="space-y-7"><label className="block space-y-2"><span className="text-sm font-medium">Phone number</span><div className="flex items-center border-b border-input focus-within:border-primary"><span className="pb-3 text-muted-foreground">+95</span><input {...phoneField} value={formatMyanmarPhoneInput(phoneValue)} onChange={(event) => setValue("phone_number", normalizeMyanmarPhoneInput(event.target.value), { shouldValidate: true })} inputMode="tel" placeholder="9 753630248" className="h-12 flex-1 border-0 bg-transparent px-2 outline-none" /></div>{errors.phone_number ? <p className="text-sm text-destructive">{errors.phone_number.message}</p> : null}</label><label className="block space-y-2"><span className="text-sm font-medium">NRC number</span><input {...register("nrc_number")} placeholder="12/ABC(N)123456" className="h-12 w-full border-0 border-b border-input bg-transparent px-0 outline-none focus:border-primary" />{errors.nrc_number ? <p className="text-sm text-destructive">{errors.nrc_number.message}</p> : null}</label><label className="block space-y-2"><span className="text-sm font-medium">Company name</span><input {...register("company_name")} placeholder="Your company or team" className="h-12 w-full border-0 border-b border-input bg-transparent px-0 outline-none focus:border-primary" />{errors.company_name ? <p className="text-sm text-destructive">{errors.company_name.message}</p> : null}</label><fieldset className="space-y-3"><legend className="text-sm font-medium">What industry are you in?</legend><div className="flex flex-wrap gap-2">{industries.map((item) => <button key={item} type="button" onClick={() => setValue("industry", item, { shouldValidate: true })} className={`rounded-full border px-4 py-2 text-sm transition ${industry === item ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background hover:border-primary"}`}>{item}</button>)}</div><input {...register("other_industry")} onChange={(event) => { setValue("other_industry", event.target.value); setValue("industry", event.target.value, { shouldValidate: true }); }} placeholder="Others, tell us more" className="h-12 w-full border-0 border-b border-input bg-transparent px-0 outline-none focus:border-primary" />{errors.industry ? <p className="text-sm text-destructive">{errors.industry.message}</p> : null}</fieldset></div>;
}
