"use client";

import { Activity, ArrowRight, BriefcaseBusiness, ClipboardCheck, Compass, Inbox, Package, RefreshCw, Sparkles, WalletCards } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useDashboardSummary } from "@/features/dashboard/dashboard-api";
import { useNotifications } from "@/features/notifications/notifications-api";
import { getNotificationCategoryLabel, getNotificationLink } from "@/features/notifications/notifications-types";
import { useAppStore, type AppRole } from "@/store/use-app-store";

function formatMmk(value: string): string { return `${new Intl.NumberFormat("en-US").format(Number(value))} MMK`; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function getErrorMessage(error: unknown): string { return error instanceof Error && error.message.length > 0 ? error.message : "Refresh and try again."; }
function roleCopy(role: AppRole): { eyebrow: string; title: string; description: string } {
  return role === "CLIENT" ? { eyebrow: "Client workspace", title: "Keep your projects moving", description: "See what needs your attention, then return to the right workroom in one click." } : { eyebrow: "Freelancer workspace", title: "Make progress with confidence", description: "Stay close to active work, escrow updates, and client review decisions." };
}
function actionCopy(action: string): string { if (action === "VIEW_ESCROW_STATUS") return "View escrow status"; if (action === "REVIEW_DELIVERABLE") return "Review submitted work"; if (action === "VIEW_REVIEW_STATUS") return "View review status"; return "Open workroom"; }
function metricIcon(key: string): ReactNode { if (key === "AWAITING_ESCROW") return <WalletCards aria-hidden="true" />; if (key === "IN_REVIEW") return <ClipboardCheck aria-hidden="true" />; return <BriefcaseBusiness aria-hidden="true" />; }
function statusLabel(status: string): string { if (status === "AWAITING_ESCROW") return "Awaiting escrow"; if (status === "IN_REVIEW") return "In review"; return "Active"; }

export function DashboardPage(): ReactNode {
  const activeRole = useAppStore((state) => state.activeRole);
  const summaryQuery = useDashboardSummary();
  const notificationsQuery = useNotifications("ALL", 5);
  const copy = roleCopy(activeRole);
  return <div className="mx-auto flex w-full max-w-6xl flex-col gap-8 p-5 sm:p-8 lg:p-10">
    <header className="flex flex-col gap-3"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary"><Sparkles aria-hidden="true" />{copy.eyebrow}</p><h1 className="font-heading text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{copy.title}</h1><p className="max-w-[58ch] text-base leading-7 text-muted-foreground">{copy.description}</p></header>
    {summaryQuery.isPending ? <DashboardSkeleton /> : summaryQuery.isError ? <Alert variant="destructive" role="alert"><RefreshCw aria-hidden="true" /><AlertTitle>Your workspace could not be loaded.</AlertTitle><AlertDescription className="flex flex-wrap items-center gap-3"><span>{getErrorMessage(summaryQuery.error)}</span><Button type="button" variant="outline" size="sm" onClick={() => { void summaryQuery.refetch(); }}>Retry</Button></AlertDescription></Alert> : <><section aria-labelledby="dashboard-metrics-heading"><h2 id="dashboard-metrics-heading" className="sr-only">Workspace summary</h2><div className="grid gap-4 md:grid-cols-3">{summaryQuery.data.metrics.map((metric) => <MetricCard key={metric.key} metric={metric} icon={metricIcon(metric.key)} />)}</div></section>{summaryQuery.data.attention_items.length > 0 ? <AttentionSection role={activeRole} items={summaryQuery.data.attention_items} /> : <RoleEmptyState role={activeRole} />}</>}
    <ActivitySection notifications={notificationsQuery.data?.items ?? []} isLoading={notificationsQuery.isPending} isError={notificationsQuery.isError} />
  </div>;
}

function MetricCard({ metric, icon }: { metric: { key: string; label: string; count: number }; icon: ReactNode }): ReactNode { return <Card className="min-h-36 border-border/80 shadow-sm"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardDescription>{metric.label}</CardDescription><CardTitle className="mt-2 text-3xl">{metric.count}</CardTitle></div><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</span></CardHeader><CardContent><p className="text-xs text-muted-foreground">From your current workspace view</p></CardContent></Card>; }

type DashboardItem = { order_id: string; title: string; participant: { id: string; full_name: string | null; avatar_url: string | null }; status: string; amount_mmk: string; updated_at: string; action: string };

function AttentionSection({ role, items }: { role: AppRole; items: DashboardItem[] }): ReactNode { return <Card className="overflow-hidden border-border/80 shadow-sm" aria-labelledby="attention-heading"><CardHeader className="border-b border-border"><div className="flex items-start justify-between gap-4"><div><CardTitle id="attention-heading">Needs your attention</CardTitle><CardDescription className="mt-1">The next few decisions that keep work moving.</CardDescription></div><Link href="/orders" className="hidden min-h-10 items-center gap-1 rounded-md px-2 text-sm font-medium text-primary hover:bg-muted focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 sm:inline-flex">View all <ArrowRight aria-hidden="true" className="size-4" /></Link></div></CardHeader><CardContent className="p-0"><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>{role === "CLIENT" ? "Freelancer" : "Client"}</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead>Updated</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{items.map((item) => <AttentionRow key={item.order_id} item={item} />)}</TableBody></Table></div><ul className="divide-y divide-border md:hidden" aria-label="Work requiring attention">{items.map((item) => <AttentionCard key={item.order_id} item={item} />)}</ul><div className="border-t border-border p-4 sm:hidden"><Link href="/orders" className="inline-flex min-h-10 items-center gap-1 text-sm font-medium text-primary focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">View all orders <ArrowRight aria-hidden="true" className="size-4" /></Link></div></CardContent></Card>; }

function AttentionRow({ item }: { item: DashboardItem }): ReactNode { return <TableRow><TableCell className="max-w-56"><Link href={`/messages/${item.order_id}`} className="block truncate font-medium text-foreground hover:text-primary focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{item.title}</Link></TableCell><TableCell><Participant participant={item.participant} /></TableCell><TableCell><Badge>{statusLabel(item.status)}</Badge></TableCell><TableCell><data value={item.amount_mmk}>{formatMmk(item.amount_mmk)}</data></TableCell><TableCell><time dateTime={item.updated_at} className="text-muted-foreground">{formatDate(item.updated_at)}</time></TableCell><TableCell className="text-right"><Link href={`/messages/${item.order_id}`} className="text-sm font-semibold text-primary hover:underline focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{actionCopy(item.action)}</Link></TableCell></TableRow>; }
function AttentionCard({ item }: { item: DashboardItem }): ReactNode { return <li className="p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><Link href={`/messages/${item.order_id}`} className="block truncate font-semibold text-foreground focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{item.title}</Link><div className="mt-2"><Participant participant={item.participant} /></div></div><Badge className="shrink-0">{statusLabel(item.status)}</Badge></div><div className="mt-4 flex items-center justify-between gap-4 text-sm"><span className="font-medium">{formatMmk(item.amount_mmk)}</span><time dateTime={item.updated_at} className="text-muted-foreground">{formatDate(item.updated_at)}</time></div><Link href={`/messages/${item.order_id}`} className="mt-4 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-primary focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{actionCopy(item.action)} <ArrowRight aria-hidden="true" className="size-4" /></Link></li>; }
function Participant({ participant }: { participant: { full_name: string | null; avatar_url: string | null } }): ReactNode { const name = participant.full_name?.trim() || "Workspace participant"; return <span className="flex min-w-0 items-center gap-2"><Avatar size="sm"><AvatarImage src={participant.avatar_url ?? undefined} alt="" /><AvatarFallback>{name.slice(0, 1).toUpperCase()}</AvatarFallback></Avatar><span className="truncate text-sm">{name}</span></span>; }
function RoleEmptyState({ role }: { role: AppRole }): ReactNode { const client = role === "CLIENT"; return <Card className="border-dashed border-border bg-muted/20"><CardContent className="p-8 sm:p-12"><Empty><EmptyHeader><EmptyMedia variant="icon">{client ? <Compass aria-hidden="true" /> : <Package aria-hidden="true" />}</EmptyMedia><EmptyTitle>{client ? "Your next project starts here" : "Your workspace is ready for new work"}</EmptyTitle><EmptyDescription>{client ? "Find trusted talent or shape a brief for your next project." : "Create a package for clients to discover, or find work that fits your skills."}</EmptyDescription></EmptyHeader><EmptyContent className="mt-5 flex-wrap"><Link className={buttonVariants()} href={client ? "/find-talent" : "/posts/new"}>{client ? "Find talent" : "Create a package"}</Link><Link className={buttonVariants({ variant: "outline" })} href={client ? "/posts/new" : "/find-work"}>{client ? "Create job post" : "Find work"}</Link></EmptyContent></Empty></CardContent></Card>; }
function ActivitySection({ notifications, isLoading, isError }: { notifications: Array<{ id: string; title: string; body: string | null; category: "SYSTEM_ACCOUNT" | "ORDERS_ESCROW" | "OFFERS_PROPOSALS"; created_at: string; metadata: Record<string, unknown>; is_read: boolean }>; isLoading: boolean; isError: boolean }): ReactNode { return <Card className="border-border/80 shadow-sm" aria-labelledby="activity-heading"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle id="activity-heading">Recent activity</CardTitle><CardDescription className="mt-1">The latest signals from your account and work.</CardDescription></div><Link href="/notifications" className="inline-flex min-h-10 items-center gap-1 text-sm font-medium text-primary hover:underline focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">See all <ArrowRight aria-hidden="true" className="size-4" /></Link></div></CardHeader><CardContent>{isLoading ? <div className="space-y-3" role="status" aria-label="Loading recent activity">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-14 w-full rounded-xl" />)}</div> : isError ? <p className="text-sm text-muted-foreground">Recent activity is unavailable. Your work summary is still available.</p> : notifications.length === 0 ? <div className="flex items-center gap-3 rounded-xl border border-dashed border-border bg-muted/20 p-4"><Inbox aria-hidden="true" className="size-5 text-muted-foreground" /><p className="text-sm text-muted-foreground">New order and account updates will appear here.</p></div> : <ul className="divide-y divide-border">{notifications.map((notification) => <li key={notification.id} className="flex items-start gap-3 py-3 first:pt-0 last:pb-0"><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Activity aria-hidden="true" className="size-4" /></span><Link href={getNotificationLink(notification) ?? "/notifications"} className="min-w-0 flex-1 rounded-md focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50"><span className="block truncate text-sm font-medium">{notification.title}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{notification.body ?? getNotificationCategoryLabel(notification.category)} · {formatDate(notification.created_at)}</span></Link></li>)}</ul>}</CardContent></Card>; }
function DashboardSkeleton(): ReactNode { return <div className="space-y-6" role="status" aria-label="Loading your workspace"><div className="grid gap-4 md:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-36 rounded-xl" />)}</div><Skeleton className="h-72 rounded-xl" /></div>; }
