"use client";
import { useState } from 'react'; import type { FreelancerSampleWork, SampleWorkUpdate } from 'shared/schemas'; import { Button } from '@/components/ui/button'; import { useCreateSampleWork, useDeleteSampleWork, useReorderSampleWorks, useSampleWorks, useUpdateSampleWork } from '@/features/sample-work/sample-work-hooks'; import { SampleWorkCard } from './sample-work-card'; import { SampleWorkForm } from './sample-work-form';
import { useAppStore } from '@/store/use-app-store';
export function FreelancerSampleWorkSection() {
  const activeRole = useAppStore((state) => state.activeRole); const isFreelancer = activeRole === 'FREELANCER'; const query = useSampleWorks(isFreelancer); const create = useCreateSampleWork(); const update = useUpdateSampleWork(); const remove = useDeleteSampleWork(); const reorder = useReorderSampleWorks(); const [editing, setEditing] = useState<FreelancerSampleWork | null>(null); const [formOpen, setFormOpen] = useState(false); const [items, setItems] = useState<FreelancerSampleWork[]>([]); const displayedItems = items.length > 0 ? items : query.data?.items ?? []; const busy = create.isPending || update.isPending;
  function move(index: number, direction: -1 | 1): void { const next = [...displayedItems]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setItems(next); }
  function saveOrder(): void { if (displayedItems.length === 0) return; reorder.mutate({ sampleIds: displayedItems.map((item) => item.id) }, { onSuccess: () => setItems([]) }); }
  if (!isFreelancer) return <section className="rounded-2xl border border-border bg-card p-6" aria-labelledby="sample-work-access-heading"><h2 id="sample-work-access-heading" className="font-heading text-xl font-semibold text-foreground">Freelancer settings</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Sample work is available when you switch to Freelancer view. Client accounts cannot manage freelancer portfolio samples.</p></section>;
  if (query.isPending) return <section className="rounded-2xl border border-border bg-card p-6" aria-busy="true">Loading your portfolio…</section>;
  if (query.isError) return <section className="rounded-2xl border border-destructive/30 bg-card p-6 text-sm text-destructive" role="alert">Your sample work could not be loaded. Refresh and try again.</section>;
  return <section className="space-y-6" aria-labelledby="sample-work-heading"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary">Freelancer portfolio</p><h1 id="sample-work-heading" className="mt-2 font-heading text-3xl font-semibold tracking-tight text-foreground">Sample work</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Show up to six independent examples of your work. These samples are separate from your packages.</p></div><Button type="button" onClick={() => { setEditing(null); setFormOpen(true); }} disabled={displayedItems.length >= 6}>Add sample work</Button></header>{formOpen ? <SampleWorkForm key={editing?.id ?? 'new'} existing={editing ?? undefined} busy={busy} onCancel={() => setFormOpen(false)} onSubmit={(input, file) => { if (editing) { const updateInput: SampleWorkUpdate = input; update.mutate({ id: editing.id, input: updateInput, file }, { onSuccess: () => { setFormOpen(false); setEditing(null); } }); } else if (file) { create.mutate({ input, file }, { onSuccess: () => setFormOpen(false) }); } }} /> : null}<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{displayedItems.map((item, index) => <div key={item.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const draggedId = event.dataTransfer.getData('text/plain'); const from = displayedItems.findIndex((candidate) => candidate.id === draggedId); if (from >= 0 && from !== index) { const next = [...displayedItems]; const [dragged] = next.splice(from, 1); next.splice(index, 0, dragged); setItems(next); } }}><SampleWorkCard item={item} index={index} total={displayedItems.length} onEdit={() => { setEditing(item); setFormOpen(true); }} onDelete={() => { if (window.confirm(`Delete ${item.title}?`)) remove.mutate(item.id); }} onMove={(direction) => move(index, direction)} /></div>)}{displayedItems.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-10 text-center sm:col-span-2 xl:col-span-3"><p className="font-medium text-foreground">Your portfolio is empty</p><p className="mt-2 text-sm text-muted-foreground">Add your strongest independent work so clients can evaluate your style.</p></div> : null}</div>{displayedItems.length > 0 ? <div className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{displayedItems.length} of 6 samples saved</p><Button type="button" variant="outline" disabled={reorder.isPending || items.length === 0} onClick={saveOrder}>{reorder.isPending ? 'Saving order…' : 'Save order'}</Button></div> : null}</section>;
}
