"use client";

import { MoreHorizontal, Pencil, Trash2, ToggleLeft } from "lucide-react";
import type { CatalogJobPost, JobPostStatus } from "shared/schemas";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

function money(value: string | null): string { return value === null ? "Flexible" : `${Number(value).toLocaleString("en-US")} MMK`; }
function statusClass(status: JobPostStatus): string { return status === "OPEN" ? "bg-primary/10 text-primary" : status === "HIRING" ? "bg-accent text-accent-foreground" : "bg-muted text-muted-foreground"; }

export function JobPostsTable({ jobs, userId, loading, error, onCreate, onEdit, onStatus, onDelete }: { jobs: CatalogJobPost[]; userId: string; loading: boolean; error: string | null; onCreate: () => void; onEdit: (job: CatalogJobPost) => void; onStatus: (job: CatalogJobPost, status: JobPostStatus) => void; onDelete: (job: CatalogJobPost) => void }): React.ReactNode {
  if (loading) return <div className="h-72 animate-pulse rounded-2xl border border-border bg-muted/40" role="status" aria-label="Loading job posts" />;
  if (error) return <div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-6 text-sm text-destructive" role="alert">{error}</div>;
  if (jobs.length === 0) return <section className="rounded-2xl border border-dashed border-border bg-card p-8 text-center sm:p-12"><p className="font-display text-4xl text-primary">Make the brief clear</p><h2 className="mt-3 font-heading text-2xl font-semibold">No job posts yet</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">A thoughtful brief gives the right freelancer a reason to reply.</p><Button className="mt-6" onClick={onCreate}>Create a job post</Button></section>;
  return <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Title</TableHead><TableHead>Budget</TableHead><TableHead>Deadline</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{jobs.map((job) => { const owned = job.client.user_id === userId; return <TableRow key={job.id}><TableCell className="min-w-64"><div className="font-medium text-foreground">{job.title}</div><div className="mt-1 max-w-sm truncate text-xs text-muted-foreground">{job.description}</div></TableCell><TableCell className="whitespace-nowrap font-mono text-xs">{money(job.budget_min_mmk)} <span className="text-muted-foreground">to</span> {money(job.budget_max_mmk)}</TableCell><TableCell className="whitespace-nowrap font-mono text-xs">{job.expected_deadline ? <time dateTime={job.expected_deadline}>{job.expected_deadline}</time> : "Flexible"}</TableCell><TableCell><Badge className={statusClass(job.status)}>{job.status}</Badge></TableCell><TableCell className="text-right">{owned ? <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label={`Actions for ${job.title}`}><MoreHorizontal aria-hidden="true" /></Button>} /><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onEdit(job)}><Pencil aria-hidden="true" />Edit post</DropdownMenuItem>{job.status === "OPEN" ? <DropdownMenuItem onClick={() => onStatus(job, "CLOSED")}><ToggleLeft aria-hidden="true" />Close post</DropdownMenuItem> : job.status === "CLOSED" ? <DropdownMenuItem onClick={() => onStatus(job, "OPEN")}><ToggleLeft aria-hidden="true" />Reopen post</DropdownMenuItem> : null}<DropdownMenuItem className="text-destructive" onClick={() => onDelete(job)}><Trash2 aria-hidden="true" />Delete post</DropdownMenuItem></DropdownMenuContent></DropdownMenu> : <span className="text-xs text-muted-foreground">View only</span>}</TableCell></TableRow>; })}</TableBody></Table></div></div>;
}

